### ISSUE TITLE
Linux : Pop!_OS 21.04 - Upon install and attempting to run for the first time:  "Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory"

### ISSUE THREAD

**Issue by MostHated** [dotnet-shell/Shell#3]
Hey there,
    I just installed this to give it a try, but unfortunately I was greeted with the below error the first time I tried to run it.

<details>
<summary>Error details</summary>

```sh
zsh > dotnet tool install -g dotnet-shell
You can invoke the tool using the following command: dotnet-shell
Tool 'dotnet-shell' (version '1.0.0.5') was successfully installed.

~ took 2s
zsh > dotnet-shell
This looks like the first run of dotnet-shell, do you want to run the initial set up wizard (highly recommended)?
Y|N) y

Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at FirstRunWizard.WizardUI.RunAndGetStdOut(String program, String arguments) in D:\Repos\GitHub\dotnet-shell\Shell\src\FirstRunWizard\WizardUI.cs:line 273
   at FirstRunWizard.WizardUI.DoesTmuxSupportPopups() in D:\Repos\GitHub\dotnet-shell\Shell\src\FirstRunWizard\WizardUI.cs:line 224
   at FirstRunWizard.WizardUI.IsSupportedTmuxVersionInstalled() in D:\Repos\GitHub\dotnet-shell\Shell\src\FirstRunWizard\WizardUI.cs:line 204
   at FirstRunWizard.WizardUI.PreRequisitesCheck() in D:\Repos\GitHub\dotnet-shell\Shell\src\FirstRunWizard\WizardUI.cs:line 193
   at FirstRunWizard.WizardUI.StartInteractive() in D:\Repos\GitHub\dotnet-shell\Shell\src\FirstRunWizard\WizardUI.cs:line 40
   at Dotnet.Shell.Program.Main(String[] args) in D:\Repos\GitHub\dotnet-shell\Shell\src\Shell\Program.cs:line 57
   at Dotnet.Shell.Program.<Main>(String[] args)
[1]    2096702 IOT instruction (core dumped)  dotnet-shell
```

</details>

<details>
<summary>Dotnet info</summary>

```sh
zsh > dotnet --info 
.NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     pop
 OS Version:  21.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.302/

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.405 [/usr/share/dotnet/sdk]
  5.0.103 [/usr/share/dotnet/sdk]
  5.0.302 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```

</details>

Thanks,
-MH

**Comment by i-am-shodan** [comment]
Firstly thanks for a very well prepared bug report.

I've found the issue - it's trying to check the tmux version but tmux isn't installed. I have added some handling and it should now work correctly. Please get back in touch if it doesn't.

I've uploaded a new nuget but this often takes 30m-1h to become available. Ensure you are using 1.0.0.6.

It's also worth saying that without tmux you wont get the more fancy popup windows in your terminal but everything else should work.

Please close this issue if the issue is resolved.

**Comment by MostHated** [comment]
I appreciate the reply. v1.0.0.6 was available, so I updated. I also went ahead and installed tmux, but it was an older version, so I pulled it down and built it, then reran dotnet-shell and it looks like everything is squared away. :+1: 

Thanks,
-MH
